Repository Software-Meister-High-School-Community/MOIZA_Android, pull requests merged in 2022-03, with the labels that each got.

#27 🔀 :: (#23) Sort bottom dialog
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/moizaandroid/moiza/ui/base/BaseActivity.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/board/dialog/PostSortDialog.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/category/CategoryFragment.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/main/MainActivity.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/notification/NotificationFragment.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/post/PostFragment.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/recent_search/RecentSearchFragment.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/result/ResultFragment.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/search/SearchFragment.kt
  app/src/main/java/com/moizaandroid/moiza/utils/Component.kt
  app/src/main/java/com/moizaandroid/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/bg_bottom_dialog.xml
  app/src/main/res/drawable/bg_category_box.xml
  app/src/main/res/drawable/bg_dialog_white_btn.xml
  app/src/main/res/drawable/bg_dialog_yellow_btn.xml
  app/src/main/res/drawable/bg_normal_post_btn.xml
  app/src/main/res/drawable/bg_post_btn.xml
  app/src/main/res/drawable/bg_post_sort_btn.xml
  app/src/main/res/drawable/bg_search_btn.xml
  app/src/main/res/drawable/bg_selected_post_btn.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_up_24.xml
  app/src/main/res/drawable/ic_baseline_close_24.xml
  app/src/main/res/drawable/ic_baseline_expand_more_24.xml
  app/src/main/res/drawable/ic_moiza_logo.xml
  app/src/main/res/drawable/ic_post_sort_img.xml
  app/src/main/res/drawable/ic_search_icon.xml
  app/src/main/res/drawable/ic_search_white_btn.xml
  app/src/main/res/drawable/ic_white_post_logo.xml
  app/src/main/res/drawable/sl_bottom_color.xml
  app/src/main/res/drawable/sl_post_dialog_text.xml
  app/src/main/res/drawable/sl_post_radio_seletor.xml
  app/src/main/res/drawable/sl_post_text_color.xml
  app/src/main/res/drawable/sl_sort_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_post_sort.xml
  app/src/main/res/layout/dialog_search_sort.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/fragment_recent_search.xml
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/board_fragment_graph.xml
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#31 📑 Radius setting code 수정
  app/src/main/java/com/moizaandroid/moiza/ui/component/board/dialog/PostSortDialog.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/post/PostFragment.kt
Labels: Chore

#37 🔀 :: (#35) transfer compose
  app/src/main/java/com/moizaandroid/moiza/ui/component/CheckBox.kt
  app/src/main/java/com/moizaandroid/moiza/ui/component/YellowButton.kt
  app/src/main/java/com/moizaandroid/moiza/ui/login/SignInActivity.kt
  app/src/main/java/com/moizaandroid/moiza/ui/login/SignInScreen.kt
  app/src/main/java/com/moizaandroid/moiza/ui/theme/Color.kt
  app/src/main/java/com/moizaandroid/moiza/ui/theme/Theme.kt
  app/src/main/java/com/moizaandroid/moiza/ui/theme/Type.kt
  app/src/main/res/drawable/ic_pw_invisible.xml
  app/src/main/res/drawable/ic_pw_visible.xml
Labels: 기능 추가, 리펙토링
